### ISSUE TITLE
Can this run on a php server?

### ISSUE THREAD

**Issue by mantismamita** [MikeKovarik/exifr#7]
Hello, does exifr require a node server or can it be used on a php server running a React application? I noticed if requires fs.

```
if (isNode) {
		if (typeof require === 'function')
			var fsPromise = Promise.resolve(require('fs').promises);
		else
			var fsPromise = import('fs').then(module => module.promises);
	}
```

**Comment by mantismamita** [comment]
Hello, I am looking to use your module on (React) application that runs on a php server. Does exifr require a node server to make use of fs?

**Comment by mantismamita** [comment]
Sorry I misclicked and closed the issue.

**Comment by MikeKovarik** [comment]
Hello. This is a JavaScript library so it needs JS environment - browser or Node.js. Both have different APIs. Node uses `fs` to read the files from disk, which is not available to browsers. That's why `fs` is optional.

If php/apache on your server only serves files, then you can use exifr on the frontend of your app.

If your php server needs to process the images, then no. you cannot use exifr.

**Comment by mantismamita** [comment]
Cheers for the quick response. I was indeed planning on using from the front end and just wanted to check that the fs was indeed optional as I was having problems with the build (which is through Webpack and hence in a node environment.) Many thanks for your work on the lib.

**Comment by MikeKovarik** [comment]
Oh, okay. So that's what it's about :D. Actually I was just discussing wepback with someone over emails. I have not yet had time to include the result into readme because i am currently working on other issues. But this is what he came up with.

```
Hi Mike,

I finally got it to work. Your code changes are fine, but it turned out that I had to make some webpack config changes to get it to work. Maybe you want to add this to the docu of exifr:

For WebPack to work I had to add:

node: {
    fs: 'empty'
},

to the general webpack.config.js. For the specific webworker module config that includes exifr I had to add:

target: "webworker",

So, exifr works now out of the box. Thanks again for your support.
Best regards,
Christian.
```

**Comment by mantismamita** [comment]
Yes, indeed 😄 
It worked fine inside Create React App but one I built it into the rest of the site I started to have issues. 
I added @babel/plugin-syntax-dynamic-import to my babel config and also 
```
node: {
    fs: 'empty'
}
```
That fixed the build problems but then when it did build I got errors in the console that exif.parse is not a function. It seems to be having trouble finding parsing the module once built which was why I asked about fs. 

I'll try adding 
```
target: "web" 
```
to the config tomorrow and report back. 
Thanks again for your help (and Christian too 😄 )

**Comment by mantismamita** [comment]
Hello, just reporting back that all is well with the two options above in the Webpack config. No need for the babel plugin for dynamic imports as it no longer enters into the isNode condition.

**Comment by MikeKovarik** [comment]
Hello, thanks for getting back to me. Today i experimented with webpack and found out there's another way. I added webpacks magic comment that prevents including 'fs' in the bundle. I didn't like it at first because I want the library to be agnostic, but Parcel seems to work out of the box and with this little change I'll same some time to a lot of people like you.
I also closed #11 and added more info about bundling to readme.
2.1.1 was released. With that you may not need the above mentioned webpack config properties.

**Comment by mantismamita** [comment]
Ok thanks, I'll try 2.1.1 and get back to you if there are any problems.

**Comment by mantismamita** [comment]
So to follow up:
when I update to 2.1.1 I still get the following error when I remove
```
node: {
    fs: 'empty'
},
target: 'web',
```
```
ERROR in ../node_modules/exifr/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/k.cassid/Projects/provision/apps/xxxxx/statics/node_modules/exifr'
 ```

Not really a problem though as I don't don't mind updating the webpack config. 😄 

I have another issue that may or may not be related to webpack but I'll ask that as a new issue.

**Comment by MikeKovarik** [comment]
Oh bummer. I tried the 2.1.1 on very simple webpack project and it worked. But it doesn't seem to work out of the box. At least we know what to do about it
